language: python
python: 2.7

sudo: false
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  edge: true
  directories:
    - $HOME/.build
    - $HOME/.cache/pip

virtualenv:
  system_site_packages: true

before_install:
  - pip install pip --upgrade

install:
  - pip install pylint
  - pip install bashate
  - pip install flake8

script:
  - python .travis/build.py
